from fastapi import FastAPI, HTTPException, BackgroundTasks, UploadFile, File, Form
from fastapi.responses import FileResponse
from app.models.schemas import PlannerRequest
from app.core.route_planner import plan_routes_from_safe_airspace
from app.core.parsers.factory import BoundaryParserFactory
import tempfile
import os

app = FastAPI(title="DJI Route Planner API")

def remove_file(path: str):
    try:
        if os.path.exists(path):
            os.remove(path)
    except Exception:
        pass

def execute_planning_pipeline(polygon, request_params: dict, background_tasks: BackgroundTasks) -> FileResponse:
    try:
        # Create temporary files for input and output
        with tempfile.NamedTemporaryFile(delete=False, suffix=".geojson", mode="w") as tmp_in:
            # write out the polygon as geojson string to be read by route_planner
            import json
            from shapely.geometry import mapping
            geojson_dict = {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "geometry": mapping(polygon),
                        "properties": {}
                    }
                ]
            }
            json.dump(geojson_dict, tmp_in)
            input_file = tmp_in.name

        with tempfile.NamedTemporaryFile(delete=False, suffix=".kmz") as tmp_out:
            output_file = tmp_out.name

        camera_info = {
            "fov_horizontal_deg": request_params.get('fov_h', 84.0),
            "fov_vertical_deg": request_params.get('fov_v', 60.0)
        }

        # Call the core routing logic
        plan_routes_from_safe_airspace(
            safe_airspace_file=input_file,
            flight_alt_agl=request_params.get('agl', 120.0),
            flight_speed=request_params.get('speed', 10.0),
            camera_info=camera_info,
            forward_overlap=request_params.get('overlap_f', 0.8),
            side_overlap=request_params.get('overlap_s', 0.7),
            output_kmz=output_file,
            waypoint_mode=request_params.get('waypoint_mode', 'sparse'),
            drone_enum=request_params.get('drone_enum', 95),
            payload_enum=request_params.get('payload_enum', 52)
        )

        # Ensure the output file exists
        if not os.path.exists(output_file):
            raise HTTPException(status_code=500, detail="Failed to generate KMZ file")

        # Clean up input file right away, output file after sending
        remove_file(input_file)

        # Cleanup tasks after response is sent
        background_tasks.add_task(remove_file, output_file)
        # Also clean up the geojson generated by route_planner if it exists
        geojson_out = output_file.replace('.kmz', '_waypoints.geojson')
        background_tasks.add_task(remove_file, geojson_out)

        return FileResponse(
            path=output_file,
            media_type="application/vnd.google-earth.kmz",
            filename="flight_routes.kmz"
        )

    except ValueError as e:
        # custom exception like mapping custom invalid geometry
        if 'input_file' in locals():
            remove_file(input_file)
        if 'output_file' in locals():
            remove_file(output_file)
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        # Cleanup on failure
        if 'input_file' in locals():
            remove_file(input_file)
        if 'output_file' in locals():
            remove_file(output_file)
        raise HTTPException(status_code=500, detail=f"Internal calculation failure: {str(e)}")


@app.post("/api/v1/planner/generate_kmz")
def generate_kmz(request: PlannerRequest, background_tasks: BackgroundTasks):
    try:
        parser = BoundaryParserFactory.get_parser("geojson")()
        polygon = parser.parse(request.boundary_geojson)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to parse geojson: {str(e)}")

    request_params = request.model_dump()
    return execute_planning_pipeline(polygon, request_params, background_tasks)

@app.post("/api/v1/planner/generate_kmz_from_file")
async def generate_kmz_from_file(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(..., description="Upload .kml or .geojson file"),
    fov_h: float = Form(84.0),
    fov_v: float = Form(60.0),
    agl: float = Form(120.0),
    speed: float = Form(10.0),
    overlap_f: float = Form(0.8),
    overlap_s: float = Form(0.7),
    drone_enum: int = Form(95),
    payload_enum: int = Form(52),
    waypoint_mode: str = Form("sparse")
):
    ext = os.path.splitext(file.filename)[1]
    if not ext:
        raise HTTPException(status_code=400, detail="File must have an extension (.kml, .geojson, .json)")

    try:
        parser_cls = BoundaryParserFactory.get_parser(ext)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    try:
        content = await file.read()
        parser = parser_cls()
        polygon = parser.parse(content)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to parse file: {str(e)}")

    request_params = {
        "fov_h": fov_h,
        "fov_v": fov_v,
        "agl": agl,
        "speed": speed,
        "overlap_f": overlap_f,
        "overlap_s": overlap_s,
        "drone_enum": drone_enum,
        "payload_enum": payload_enum,
        "waypoint_mode": waypoint_mode
    }
    return execute_planning_pipeline(polygon, request_params, background_tasks)
